# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4027c2ba645002ff7b63a2afdf3e553bb777cbbfe4328df6efabd566623ea530dcfc852e8b6a1aeac5b1749dc14e65e15a545eed2324a98256031c76e20d0074

test:
  secret_key_base: 1cd25a47d64618cb6137774c4ac8e79567c212786a705f6aad7c88e584f946441be59b5a70a46c56739afd056129089ebf14fdc8d941142df78c5b9503a7d6d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
